
name: publish

on:
  workflow_dispatch:
    inputs:
      # Dhis2 version to build
      version:
        description: "version of dhis2 to build (eg: 2.33.8), please verify before locally you don't need dhis.conf adaptations. See https://github.com/BLSQ/ops-dhis2-images#testing-locally"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish image
        run: ./script/release ${{github.event.inputs.version }}

