
name: deploy

on:
  workflow_dispatch:
    inputs:
      # Dhis2 version to build
      version:
        description: version of dhis2 to build
        required: true
  push:
    # On push to main deploy to staging
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Dependencies
        run: ./script/release ${{github.event.inputs.version }}

